### ISSUE TITLE
KMSCON confustion

### ISSUE THREAD

**Issue by keshto** [MacSlow/haskell-gimmicks#1]
Your `kmscon` repo does not have issues enabled, so putting here to get your attention  (I couldn't find an email or other way to contact you).

- Clean up the repo (kmscon): `master` should point to your latest changes so people who are searching don't land and think there is no development going on.
- Update README to include relationship with Aetf/ repo and maybe specify how the releases there don't include your changes.

**Comment by MacSlow** [comment]
Gee... I left this open. Issues are enabled for some time now... closing this one.
